name: Deploy personal website frontend
on:
  push:
    branches:
      - "main"

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
    
    - name: checkout repo 
      uses: actions/checkout@v3 
    
    - name: configure nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: build react application 
      run: |
        npm install
        npm run build 
    
    - name: deploy to static web apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APP_API_TOKEN}}
        app_location: /
        output_location: build